name = input("안녕하세요. 당신의 이름은 무엇인가요? ")
print("반갑습니다. %s님." %name[1:3])
height = float(input("당신의 키는 몇입니까? "))
weight = float(input("당신의 몸무게는 몇인가요? "))
print("키 : %s" %height)
print("몸무게 : %s" %weight)
