print("계산기")
num1 = int(input("숫자1를 입력하세요"))
num2 = int(input("숫자2를 입력하세요"))
print("%d + %d =%d" %(num1, num2, num1 + num2))
print("%d - %d = %d" %(num1, num2, num1 - num2))
print("%d X %d = %d" %(num1, num2, num1 * num2))
print("%d / %d = %.2f" %(num1, num2, num1 / num2))
print("%d // %.d = %d" %(num1, num2, num1 // num2))
print("%d 나머지만구하기 %d = %d" %(num1, num2, num1 % num2))
